### ISSUE TITLE
Implement new scribble v5.0.0 version

### ISSUE THREAD

**Issue by glitchroy** [glitchroy/textboxy#32]
[Scribble v5.0.0](https://github.com/JujuAdams/scribble) has been released and brings a whole lot of new stuff.  

#### To-Do
- [x] Replace scripts
- [x] Adjust config file
- [x] Adjust init script
- [x] Adjust script calls in textbox object
- [x] Implement cache-system on a per-branch level

Tracked in `/feature/scribble-5.0.0` branch.
